version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users
      - PORT=8080
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - db

    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users?sslmode=disable
    command: >
      goose -dir=./migrations postgres 
      "postgres://postgres:postgres@db:5432/users?sslmode=disable" up



volumes:
  postgres_data:
